#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

version="0.1"

rm --force "../apparmor-profile-torbrowser_$version.orig.tar.gz"

git archive \
   --format=tar HEAD \
   | gzip -n > "../apparmor-profile-torbrowser_$version.orig.tar.gz"

if [ ! "$?" = "0" ]; then
   exit 1
fi

ls -la "../apparmor-profile-torbrowser_$version.orig.tar.gz"

debuild

if [ ! "$?" = "0" ]; then
   exit 1
fi
